version: "3.9"

services:
  api:
    build:
      context: .
    container_name: mj-api
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/api
      - ./data/web:/vol/web
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    container_name: mj-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devphotonerpdb
      - POSTGRES_PASSWORD=devphotonerpdbpassword
      - POSTGRES_USER=devphotonerpdbuser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "POSTGRES_DB", "POSTGRES_USER"]
      interval: 10s
      retries: 10
      timeout: 45s
    restart: always

volumes:
  pgdata:
    driver: local
